apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-server
  namespace: manage
  labels:
    app: consul
    role: server
data:
  server.json: |-
    {
        "skip_leave_on_interrupt": true,
        "disable_host_node_id": false,
        "leave_on_terminate" : false,
        "client_addr": "0.0.0.0",
        "datacenter": "dc1",
        "bind_addr": "0.0.0.0",
        "ca_file": "/etc/tls/ca.pem",
        "cert_file": "/etc/tls/consul.pem",
        "data_dir": "/consul/data",
        "domain": "cluster.local",
        "key_file": "/etc/tls/consul-key.pem",
        "ports": {
          "https": 8443
        },
        "retry_join": [
          "provider=k8s label_selector=\"app=consul,component=server\""
        ],
        "server": true,
        "telemetry": {
          "prometheus_retention_time": "5m"
        },
        "verify_incoming": true,
        "verify_outgoing": true,
        "verify_server_hostname": true,
        "ui": true
    }
#        "bootstrap_expect": 3,
